# Generated by Django 4.1.1 on 2022-09-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="expenses_monthly",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="data",
            name="income_monthly",
            field=models.IntegerField(default=0),
        ),
    ]
